[package]
name = "adxl345-game-coordinator"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.myrmic]
heap_size = 16_384

[lints]
workspace = true

[dependencies]
myrmic-sdk = { workspace = true }
myrmic-sdk-macros = { workspace = true }
serde = { workspace = true }
