[package]
name = "adxl345-driver"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
embedded-hal-async = "1"
log = { version = "0.4", default-features = false }

[dev-dependencies]
embedded-hal-mock = { version = "0.11", features = ["embedded-hal-async"] }
futures = { version = "0.3", features = ["executor"] }
