[package]
name = "adxl345-tap-cell"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[package.metadata.myrmic]
heap_size = 8_192

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
myrmic-sdk        = { workspace = true }
myrmic-sdk-macros = { workspace = true }
signal-layer-types = { workspace = true }
